/** Generated by TAP **/
KISSY.config({
    "modules": {},
    "packages": {
        "pegasus/<%= project %>": {
            "debug": true,
            "ignorePackageNameInUri": true,
            "version": "<%= version %>",
            "path": "//g.alicdn.com/pegasus/pegasus-test/<%= version %>/",
            "group": "tm"
        }
    },
    "version": "1.4.10",
});
